pico2wave -l de-DE -w firmware_tts_00.wav "Taste 0"
pico2wave -l de-DE -w firmware_tts_01.wav "Taste 1"
pico2wave -l de-DE -w firmware_tts_02.wav "Taste 2"
pico2wave -l de-DE -w firmware_tts_03.wav "Taste 3"
pico2wave -l de-DE -w firmware_tts_04.wav "Taste 4"
pico2wave -l de-DE -w firmware_tts_05.wav "Taste 5"
pico2wave -l de-DE -w firmware_tts_06.wav "Taste 6"
pico2wave -l de-DE -w firmware_tts_07.wav "Taste 7"
pico2wave -l de-DE -w firmware_tts_08.wav "Taste 8"
pico2wave -l de-DE -w firmware_tts_09.wav "Null"
pico2wave -l de-DE -w firmware_tts_10.wav "Eins"
pico2wave -l de-DE -w firmware_tts_11.wav "Zwei"
pico2wave -l de-DE -w firmware_tts_12.wav "Drei"
pico2wave -l de-DE -w firmware_tts_13.wav "Vier"
pico2wave -l de-DE -w firmware_tts_14.wav "Fünf"
pico2wave -l de-DE -w firmware_tts_15.wav "Sechs"
pico2wave -l de-DE -w firmware_tts_16.wav "Sieben"
pico2wave -l de-DE -w firmware_tts_17.wav "Acht"
pico2wave -l de-DE -w firmware_tts_18.wav "Neun"
pico2wave -l en-US -w firmware_tts_19.wav "starting up"
pico2wave -l en-US -w firmware_tts_20.wav "shutting down"
pico2wave -l en-US -w firmware_tts_21.wav "ping"
pico2wave -l en-US -w firmware_tts_22.wav "chord"
pico2wave -l de-DE -w firmware_tts_23.wav "Die Batterien sind bald leer. Bitte wechsele die Batterien nach dieser Spielrunde."
pico2wave -l de-DE -w firmware_tts_24.wav "Die Firmware des Tiptoi wird aktualisiert. Bitte schalte auf keinen Fall den Stift aus und entferne auch nicht die Batterien."
pico2wave -l de-DE -w firmware_tts_25.wav "Die Firmware wurde erfolgreich aktualisiert. Der Stift schaltet sich nun wieder an."
pico2wave -l de-DE -w firmware_tts_26.wav "Die Batterien sind leer. Der Stift schaltet sich nun ab."
pico2wave -l en-US -w firmware_tts_27.wav "Testmode"
pico2wave -l en-US -w firmware_tts_28.wav "Start test of program"
pico2wave -l en-US -w firmware_tts_29.wav "Program test pass"
pico2wave -l en-US -w firmware_tts_30.wav "Program test fail"
pico2wave -l en-US -w firmware_tts_31.wav "Start test of the tip of the pen"
pico2wave -l en-US -w firmware_tts_32.wav "Test of the tip of the pen passed"
pico2wave -l en-US -w firmware_tts_33.wav "Communication to the tip of the pen failed"
pico2wave -l en-US -w firmware_tts_34.wav "Start test of encryption procedure"
pico2wave -l en-US -w firmware_tts_35.wav "Encryption procedure test passed"
pico2wave -l en-US -w firmware_tts_36.wav "Encryption procedure test failed"
pico2wave -l en-US -w firmware_tts_37.wav "Start test of UDISK file"
pico2wave -l en-US -w firmware_tts_38.wav "Test of UDISK file passed"
pico2wave -l en-US -w firmware_tts_39.wav "Test of UDISK file failed"
pico2wave -l en-US -w firmware_tts_40.wav "Start test of SD card file"
pico2wave -l en-US -w firmware_tts_41.wav "Test of SD card file passed"
pico2wave -l en-US -w firmware_tts_42.wav "Test of SD card file failed"
pico2wave -l de-DE -w firmware_tts_43.wav "Bitte berühre zuerst das Anschaltzeichen für dieses Produkt."
pico2wave -l de-DE -w firmware_tts_44.wav "Der Stift schaltet sich in einer Minute automatisch ab."
pico2wave -l de-DE -w firmware_tts_45.wav "Bitte lade zuerst die Audiodatei für dieses Produkt auf den Stift."
pico2wave -l de-DE -w firmware_tts_46.wav "Die Batterien sind zu schwach um eine neue Firmware einzuspielen. Bitte wechsele die Batterien um die Firmware zu aktualisieren."
pico2wave -l de-DE -w firmware_tts_47.wav "Wenn du die Anleitung für dieses Spiel hören möchtest, tippe auf das Infozeichen auf dem Spielplan."
